# Generated by Django 4.0.5 on 2022-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=11, verbose_name='Rut')),
                ('ciudad', models.CharField(max_length=15, verbose_name='Ciudad')),
                ('comuna', models.CharField(max_length=15, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6, verbose_name='Patente')),
                ('nombreChofer', models.CharField(max_length=30, verbose_name='Nombre Chofer')),
                ('calificacion', models.CharField(max_length=3, verbose_name='Calificacion')),
            ],
        ),
    ]
