# Generated by Django 4.0.5 on 2022-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='patente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
    ]
